name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  export_project:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    name: Export project
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Export
      uses: firebelley/godot-export@v2.6.0
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz
        relative_project_path: ./
        create_release: false
        use_preset_export_path: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux X11 amd64 build
      uses: actions/upload-artifact@v2
      with:
        name: HonestJam-Linux-X11-amd64
        path: build/linux_amd64/HonestJam-Linux-X11-amd64/
        if-no-files-found: error

    - name: Upload macOS build
      uses: actions/upload-artifact@v2
      with:
        name: HonestJam-macOS
        path: build/macos/HonestJam-macOS/
        if-no-files-found: error

    - name: Upload Windows amd64 build
      uses: actions/upload-artifact@v2
      with:
        name: HonestJam-Windows-amd64
        path: build/windows_amd64/HonestJam-Windows-amd64/
        if-no-files-found: error

    - name: Upload HTML5 build
      uses: actions/upload-artifact@v2
      with:
        name: HonestJam-HTML5
        path: build/html5/HonestJam-HTML5/
        if-no-files-found: error
